config/routes.rb
Rails.application.routes.draw do
  resources :tweets do
    put 'like', on: :member
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  #root 'application#hello'
  root 'tweets#index'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  validates :author, length: { minimum: 4 }
  validates :content, length: { in: 4..280 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def hello
    render html: "<h1>It works WASLAB05!</h1>".html_safe
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: [:like, :show, :edit, :update, :destroy]

  # GET /tweets
  # GET /tweets.json
  def index
    @tweets = Tweet.order(created_at: :desc)
    #@tweets = Tweet.all
  end
  
  def like
    @tweet.likes = @tweet.likes + 1
    @tweet.save
    redirect_to tweets_url
  end

  # GET /tweets/1
  # GET /tweets/1.json
  def show
  end

  # GET /tweets/new
  def new
    @tweet = Tweet.new
  end

  # GET /tweets/1/edit
  def edit
  end

  # POST /tweets
  # POST /tweets.json
  def create
    @tweet = Tweet.new(tweet_params)

    respond_to do |format|
      if @tweet.save
        if not session[:created_ids].nil?
          session[:created_ids] << @tweet.id
        else
          session[:created_ids] = [@tweet.id]
        end
        format.html { redirect_to tweets_url, notice: 'Tweet was successfully created.' }
        format.json { render :show, status: :created, location: tweets_url}
      else
        format.html { render :new }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tweets/1
  # PATCH/PUT /tweets/1.json
  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to tweets_url, notice: 'Tweet was successfully updated.' }
        format.json { render :show, status: :ok, location: tweets_url }
      else
        format.html { render :edit }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1
  # DELETE /tweets/1.json
  def destroy
    if session[:created_ids].nil? or session[:created_ids].exclude?(@tweet.id)
      respond_to do |format|
        format.html { redirect_to tweets_url, notice: 'You are not allowed to delete this tweet.' }
        format.json { head :Forbidden }
      end
    else
      @tweet.destroy
      respond_to do |format|
        format.html { redirect_to tweets_url, notice: 'Tweet was successfully destroyed.' }
        format.json { head :no_content }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tweet_params
      params.require(:tweet).permit(:author, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Waslab05</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tweets/_form.html.erb
<%= form_with(model: tweet) do |form| %>
  <% if tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
        <% tweet.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :author %>
    <%= form.text_field :author %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tweets/edit.html.erb
<h1>Editing Tweet</h1>

<%= render 'form', tweet: @tweet %>

<%= link_to 'Show', @tweet %> |
<%= link_to 'Back', tweets_path %>

app/views/tweets/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="wottitle">Wall of Tweets - RoR Edition 2021</h1>
<br>

<div class="walltweet">
<form action="/tweets" accept-charset="UTF-8" method="post"><input type="hidden" name="authenticity_token" value="mf7HFhaocJmI95ceFIG8AfM_WPZKm3CNTWDyBlCPMlkMuMEs_xQ4Xi11HNIRbQGopH6tY08FVTM86eV1w3g0Kg">
<table cellpadding="2" border="0">
<tbody><tr><td>Your name:</td><td><input size="70" type="text" name="tweet[author]" id="tweet_author"></td><td></td></tr>
<tr><td>Your tweet:</td><td><textarea rows="2" cols="70" name="tweet[content]" id="tweet_content"></textarea></td>
<td><input type="submit" name="commit" value="Tweet!" data-disable-with="Tweet!"></td></tr>
</tbody></table>
</form></div>

<% @tweets.each do |tweet| %>
      <br>
      <h3>...... <%= tweet.created_at %></h3>
      <div class="wotitem" id="item_154">
        <div class="likes">
        <span class="numlikes" id="showLikes_154"><%= tweet.likes %></span>
        <br>
        <span class="smallfont">people like this
        <span>
          <br>
          <h3>
            <a rel="nofollow" data-method="put" href="/tweets/154/like">like</a>
          </h3>
        </span>
        </span>
        </div>
      <div class="item">
      <h4>
        <em><%= tweet.author %></em> 
        @ </em><%= tweet.created_at %></em>
      </h4>
      <p><%= tweet.content %></p>
      <p style="text-align: right;"><a data-confirm="Are you sure?" rel="nofollow" data-method="destroy" href="/tweets/154">Destroy</a></p>
      </div>
      </div>
    <% end %>

<br>

app/views/tweets/new.html.erb
<h1>New Tweet</h1>

<%= render 'form', tweet: @tweet %>

<%= link_to 'Back', tweets_path %>

app/views/tweets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Author:</strong>
  <%= @tweet.author %>
</p>

<p>
  <strong>Content:</strong>
  <%= @tweet.content %>
</p>

<%= link_to 'Edit', edit_tweet_path(@tweet) %> |
<%= link_to 'Back', tweets_path %>